version: "3.5"
services:
  rabbitmq:
    image: abrturing/rabbitmq-swarm:3.7.4.0
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - RABBITMQ_ERLANG_COOKIE=abc
      - RABBITMQ_USE_LONGNAME=true
      - RABBITMQ_MNESIA_DIR=/var/lib/rabbitmq/mnesia
      - RABBITMQ_PLUGINS_EXPAND_DIR=/var/lib/rabbitmq/mnesia/plugins-expand
      - SERVICE_NAME={{.Service.Name}}
      - SLOT={{.Task.Slot}}
      - MASTER_SLOT=1
    networks:
      - overlay
    ports:
      # - "5672:5672"   # amqp
      - "15672:15672" # web ui

networks:
  overlay:
    # name property is introduced in docker-compose v3.5 but it's buggy, fixed in 18.04.
    # because of the bug, it is always prefixed with stack name.
    # name: rabbitmq_overlay
    driver: overlay
    attachable: true # albeit this is already the default value, explicitly setting is better.
